<?php

namespace ContainerP9QDeiy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Command_PopulateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.command.populate' shared service.
     *
     * @return \FOS\ElasticaBundle\Command\PopulateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php';

        $container->privates['fos_elastica.command.populate'] = $instance = new \FOS\ElasticaBundle\Command\PopulateCommand(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['fos_elastica.index_manager'] ?? $container->load('getFosElastica_IndexManagerService')), ($container->services['fos_elastica.pager_provider_registry'] ?? $container->load('getFosElastica_PagerProviderRegistryService')), ($container->services['fos_elastica.pager_persister_registry'] ?? $container->load('getFosElastica_PagerPersisterRegistryService')), ($container->services['fos_elastica.resetter'] ?? $container->load('getFosElastica_ResetterService')));

        $instance->setName('fos:elastica:populate');

        return $instance;
    }
}
