<?php

namespace ContainerP9QDeiy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_ObjectPersister_App_ProductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'fos_elastica.object_persister.app.products' shared service.
     *
     * @return \FOS\ElasticaBundle\Persister\ObjectPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersisterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersister.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ModelToElasticaTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ModelToElasticaAutoTransformer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/property-access/PropertyAccessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/property-access/PropertyAccessor.php';

        $a = new \FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer(['identifier' => 'id', 'index' => 'app'], ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        $a->setPropertyAccessor(($container->privates['fos_elastica.property_accessor'] ?? ($container->privates['fos_elastica.property_accessor'] = new \Symfony\Component\PropertyAccess\PropertyAccessor(false, false))));

        return $container->services['fos_elastica.object_persister.app.products'] = new \FOS\ElasticaBundle\Persister\ObjectPersister(($container->services['fos_elastica.index.app.products'] ?? $container->load('getFosElastica_Index_App_ProductsService')), $a, 'App\\Entity\\Product', ['id' => [], 'gtin' => [], 'product_name' => [], 'product_desc' => [], 'price' => [], 'currency' => [], 'category' => [], 'gender' => [], 'quantity' => [], 'size' => [], 'color' => [], 'url' => [], 'image' => [], 'image_additional' => [], 'additional' => [], 'source_video' => []], []);
    }
}
