<?php

namespace ContainerP9QDeiy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Manager_OrmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'fos_elastica.manager.orm' shared service.
     *
     * @return \FOS\ElasticaBundle\Doctrine\RepositoryManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Manager/RepositoryManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/RepositoryManager.php';

        $container->services['fos_elastica.manager.orm'] = $instance = new \FOS\ElasticaBundle\Doctrine\RepositoryManager(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->services['fos_elastica.repository_manager'] ?? $container->load('getFosElastica_RepositoryManagerService')));

        $instance->addEntity('App\\Entity\\Product', 'app/products');

        return $instance;
    }
}
