<?php

namespace ContainerJqMblxo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Index_App_ProductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'fos_elastica.index.app.products' shared service.
     *
     * @return \Elastica\Type
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ruflin/elastica/lib/Elastica/SearchableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/ruflin/elastica/lib/Elastica/Type.php';

        return $container->services['fos_elastica.index.app.products'] = ($container->services['fos_elastica.index.app'] ?? $container->load('getFosElastica_Index_AppService'))->getType('products');
    }
}
