<?php

namespace ContainerFawzvZL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P6Sn0bhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P6Sn0bh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P6Sn0bh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productFinder' => ['services', 'fos_elastica.finder.app.products', 'getFosElastica_Finder_App_ProductsService', true],
            'session' => ['services', 'session', 'getSessionService', true],
        ], [
            'productFinder' => '?',
            'session' => '?',
        ]);
    }
}
