<?php

namespace ContainerFawzvZL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Command_ResetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.command.reset' shared service.
     *
     * @return \FOS\ElasticaBundle\Command\ResetCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Command/ResetCommand.php';

        $container->privates['fos_elastica.command.reset'] = $instance = new \FOS\ElasticaBundle\Command\ResetCommand(($container->services['fos_elastica.index_manager'] ?? $container->load('getFosElastica_IndexManagerService')), ($container->services['fos_elastica.resetter'] ?? $container->load('getFosElastica_ResetterService')));

        $instance->setName('fos:elastica:reset');

        return $instance;
    }
}
