<?php

namespace ContainerFawzvZL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Client_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'fos_elastica.client.default' shared service.
     *
     * @return \FOS\ElasticaBundle\Elastica\Client
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/ruflin/elastica/lib/Elastica/Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Elastica/Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Logger/ElasticaLogger.php';

        $container->services['fos_elastica.client.default'] = $instance = new \FOS\ElasticaBundle\Elastica\Client(['connections' => [0 => ['host' => '0.0.0.0', 'port' => 9200, 'http_error_codes' => [0 => 400, 1 => 403, 2 => 404], 'ssl' => false, 'logger' => 'fos_elastica.logger', 'compression' => false, 'headers' => [], 'curl' => [], 'retryOnConflict' => 0, 'persistent' => true]], 'connectionStrategy' => 'Simple'], NULL);

        $instance->setStopwatch(NULL);
        $instance->setLogger(new \FOS\ElasticaBundle\Logger\ElasticaLogger(($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())), true));

        return $instance;
    }
}
