<?php

namespace ContainerFawzvZL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Listener_App_ProductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.listener.app.products' shared service.
     *
     * @return \FOS\ElasticaBundle\Doctrine\Listener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/Listener.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/IndexableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Provider/Indexable.php';

        return $container->privates['fos_elastica.listener.app.products'] = new \FOS\ElasticaBundle\Doctrine\Listener(($container->services['fos_elastica.object_persister.app.products'] ?? $container->load('getFosElastica_ObjectPersister_App_ProductsService')), ($container->privates['fos_elastica.indexable'] ?? ($container->privates['fos_elastica.indexable'] = new \FOS\ElasticaBundle\Provider\Indexable([]))), ['identifier' => 'id', 'indexName' => 'app', 'typeName' => 'products'], NULL);
    }
}
