<?php

namespace ContainerFawzvZL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosElastica_Command_TemplatesResetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'fos_elastica.command.templates_reset' shared service.
     *
     * @return \FOS\ElasticaBundle\Command\ResetTemplatesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/elastica-bundle/src/Command/ResetTemplatesCommand.php';

        $container->privates['fos_elastica.command.templates_reset'] = $instance = new \FOS\ElasticaBundle\Command\ResetTemplatesCommand(($container->services['fos_elastica.template_resetter'] ?? $container->load('getFosElastica_TemplateResetterService')));

        $instance->setName('fos:elastica:reset-templates');

        return $instance;
    }
}
