<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP9QDeiy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP9QDeiy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP9QDeiy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP9QDeiy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP9QDeiy\App_KernelDevDebugContainer([
    'container.build_hash' => 'P9QDeiy',
    'container.build_id' => '90daf7eb',
    'container.build_time' => 1637020176,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP9QDeiy');
