<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], ['wildcard' => '.*'], [['text', '/api/login']], [], []],
    'login-index' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], ['wildcard' => '.*'], [['text', '/login']], [], []],
    'api' => [[], ['_controller' => 'App\\Controller\\TableController::getTable'], ['wildcard' => '.*'], [['text', '/api/tables']], [], []],
    'search' => [[], ['_controller' => 'App\\Controller\\TableController::search'], ['wildcard' => '.*'], [['text', '/api/search']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], ['wildcard' => '.*'], [['text', '/home']], [], []],
    'table' => [[], ['_controller' => 'App\\Controller\\TableController::index'], ['wildcard' => '.*'], [['text', '/table']], [], []],
];
